# Generated by Django 5.2.1 on 2025-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_name',
        ),
        migrations.AlterField(
            model_name='coach',
            name='coach_type',
            field=models.CharField(choices=[('AC', 'AC'), ('ECONOMY', 'ECONOMY'), ('SLEEPER', 'SLEEPER')], max_length=10),
        ),
    ]
