# Generated by Django 5.2.1 on 2025-06-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_coach_coach_name_alter_coach_coach_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
