# Generated by Django 5.2.1 on 2025-05-22 13:19

import multiselectfield.db.fields
from django.db import migrations, models

def copy_old_day_to_multi(apps, schema_editor):
    Route = apps.get_model('myapp', 'Route')
    for route in Route.objects.all():
        if route.day_of_week_old is not None:
            route.day_of_week = [route.day_of_week_old]
            route.save()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_station_train_alter_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='day_of_week_old',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='day_of_week',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=[0], max_length=13),
        ),
        migrations.RunPython(copy_old_day_to_multi),
    ]
