# Generated by Django 5.2.1 on 2025-06-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_coach_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='day_of_reset',
            field=models.CharField(default='0', help_text='Comma-separated days (e.g. 0,2,4)', max_length=14),
        ),
    ]
