# Generated by Django 5.2.1 on 2025-05-22 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_route_day_of_week_old_alter_route_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='day_of_week_old',
        ),
    ]
