# Generated by Django 5.2.1 on 2025-06-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booking_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
